[package]
name = "opensourcecobol4j-c-glue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.20.10"
tree-sitter-c = "0.20.4"
rustop = "1.1.2"

[build-dependencies]
cc = "*"
