name: CI
on:
  push:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]
env:
  CLASSPATH: ":/usr/lib/opensourcecobol4j/libcobj.jar:/usr/lib/opensourcecobol4j/sqlite.jar"
  OC4J_C_GLUE_JNI_INCLUDE: "-I/usr/lib/jvm/temurin-11-jdk-amd64/include/ -I/usr/lib/jvm/temurin-11-jdk-amd64/include/linux/"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get install -y cproto build-essential bison flex gettext texinfo automake autoconf

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Install opensource COBOL 4J v1.0.13
      run: |
        sudo mkdir /usr/lib/opensourcecobol4j
        curl -L -o opensourcecobol4j.tar.gz -k https://github.com/opensourcecobol/opensourcecobol4j/archive/refs/tags/v1.0.13.tar.gz
        sudo curl -L -o /usr/lib/opensourcecobol4j/sqlite.jar -k https://github.com/xerial/sqlite-jdbc/releases/download/3.36.0.3/sqlite-jdbc-3.36.0.3.jar
        tar zxf opensourcecobol4j.tar.gz
        cd opensourcecobol4j-1.0.13
        ./configure --prefix=/usr/
        make
        sudo make install

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: |
        cargo build

    - name: Unit tests
      run: cargo test --verbose
    
    - name: Integration tests
      run: ./test.sh